# ⚡ ARC Agent Makefile
# ────────────────────────────────────────────────────────────
#   make          — debug build
#   make release  — optimized release build
#   make assets   — bake CSS/JS into generated Swift source
#   make install  — release + copy to ~/.local/bin
#   make update   — assets + release + install (full cycle)
#   make dev      — debug build + serve with live asset reload
#   make test     — run tests
#   make clean    — clean build artifacts
#   make dist     — create a release tarball
#   make uninstall — remove from install dir

SWIFT      := swift
BINARY     := arc
BUILD_DIR  := .build

INSTALL_DIR ?= $(HOME)/.local/bin

ASSETS_DIR  := Sources/ArcAgentCore/WebUI/Assets
GEN_DIR     := $(ASSETS_DIR)/Generated
CSS_SRC     := $(ASSETS_DIR)/styles.css
JS_SRC      := $(ASSETS_DIR)/scripts.js
GEN_SWIFT   := $(GEN_DIR)/Assets.swift

VERSION    := $(shell git describe --tags --always 2>/dev/null || echo "dev")
DIST_DIR   := dist
DIST_NAME  := arc-agent-$(VERSION)-macos-arm64

.PHONY: all build release assets install update dev test clean dist uninstall

# ── Default: debug build ──────────────────────────────────
all: build

build:
	$(SWIFT) build

# ── Release build ─────────────────────────────────────────
release:
	$(SWIFT) build -c release

# ── Bake assets: generate Swift source from canonical CSS/JS files ──
# Reads Assets/styles.css and Assets/scripts.js, produces
# Assets/Generated/Assets.swift with the contents embedded as
# static strings. This file is the production asset source.
assets: $(CSS_SRC) $(JS_SRC)
	@echo "  Baking assets..."
	@mkdir -p $(GEN_DIR)
	@printf '// Auto-generated by `make assets`. DO NOT EDIT.\n' > $(GEN_SWIFT)
	@printf '// Source: Assets/styles.css, Assets/scripts.js\n' >> $(GEN_SWIFT)
	@printf '//\n' >> $(GEN_SWIFT)
	@printf 'import Foundation\n\n' >> $(GEN_SWIFT)
	@printf 'enum Assets {\n' >> $(GEN_SWIFT)
	@printf '    /// The canonical CSS stylesheet.\n' >> $(GEN_SWIFT)
	@printf '    /// Generated from Assets/styles.css\n' >> $(GEN_SWIFT)
	@printf '    static let css: String = \"\"\"\n' >> $(GEN_SWIFT)
	@sed 's/^/    /' $(CSS_SRC) >> $(GEN_SWIFT)
	@printf '\n    \"\"\"\n\n' >> $(GEN_SWIFT)
	@printf '    /// The canonical JavaScript runtime.\n' >> $(GEN_SWIFT)
	@printf '    /// Generated from Assets/scripts.js\n' >> $(GEN_SWIFT)
	@printf '    static let js: String = \"\"\"\n' >> $(GEN_SWIFT)
	@sed 's/^/    /' $(JS_SRC) >> $(GEN_SWIFT)
	@printf '\n    \"\"\"\n}\n' >> $(GEN_SWIFT)
	@echo "  → $(GEN_SWIFT)"

# ── Install: build release and copy binary ────────────────
install: release
	@mkdir -p $(INSTALL_DIR)
	cp -f $(BUILD_DIR)/release/$(BINARY) $(INSTALL_DIR)/$(BINARY)
	@echo "  Installed $(BINARY) → $(INSTALL_DIR)/$(BINARY)"

# ── Update: full cycle — bake assets, build release, install ──
update: assets release install
	@echo "  ✅ Update complete: $(BINARY) v$(VERSION)"

# ── Dev: build debug and serve (assets served from disk) ──
dev: build
	@echo "  Starting dev server (debug mode — assets from disk)..."
	$(BUILD_DIR)/debug/$(BINARY) serve

# ── Test ──────────────────────────────────────────────────
test:
	$(SWIFT) test 2>&1

# ── Clean ─────────────────────────────────────────────────
clean:
	$(SWIFT) package clean

# ── Distribution tarball ──────────────────────────────────
dist: release
	@mkdir -p $(DIST_DIR)/$(DIST_NAME)
	cp -f $(BUILD_DIR)/release/$(BINARY) $(DIST_DIR)/$(DIST_NAME)/$(BINARY)
	cp -f README.md $(DIST_DIR)/$(DIST_NAME)/ 2>/dev/null; true
	cp -f LICENSE $(DIST_DIR)/$(DIST_NAME)/ 2>/dev/null; true
	cd $(DIST_DIR) && tar czf $(DIST_NAME).tar.gz $(DIST_NAME)
	rm -rf $(DIST_DIR)/$(DIST_NAME)
	@echo "  → $(DIST_DIR)/$(DIST_NAME).tar.gz"

# ── Uninstall ─────────────────────────────────────────────
uninstall:
	rm -f $(INSTALL_DIR)/$(BINARY)
	@echo "  Removed $(INSTALL_DIR)/$(BINARY)"
