import ArcTheme
import CryptoKit
import Foundation

// arc-agent-webui's asset generator: the vendored KaTeX files, and the served theme sheet.
//
// invoked by `ArcAssetPlugin` on every build — there is no shell script and no hand-run step.
//
//   usage: ArcAssetTool katex <vendor/katex> <out.swift>
//          ArcAssetTool theme-sheet <out.swift>
//
// both modes embed their payloads base64 so the release binary stays a single file and no
// escaping issue can corrupt a JS/CSS payload (the patch/write transport double-escapes
// backslashes; base64 sidesteps that entirely). the theme sheet's *raw* form is embedded as a
// raw string literal instead: it is css, the tool renders it from `ArcTheme`, and the server
// serves those exact bytes.

let arguments = CommandLine.arguments

func usage() -> Never {
    FileHandle.standardError.write(
        Data("usage: ArcAssetTool katex <vendor/katex> <out.swift> | ArcAssetTool theme-sheet <out.swift>\n".utf8)
    )
    exit(2)
}

let fileManager = FileManager.default

func write(_ content: String, to output: URL) throws {
    try fileManager.createDirectory(at: output.deletingLastPathComponent(), withIntermediateDirectories: true)
    try Data(content.utf8).write(to: output)
    print("wrote \(output.path) (\(content.utf8.count) bytes)")
}

func base64(_ url: URL) throws -> String {
    try Data(contentsOf: url).base64EncodedString()
}

// MARK: - katex

func generateKatex(vendor: URL, output: URL) throws {
    let jsURL = vendor.appendingPathComponent("katex.min.js")
    let cssURL = vendor.appendingPathComponent("katex.min.css")
    let fontsDir = vendor.appendingPathComponent("fonts", isDirectory: true)

    guard fileManager.fileExists(atPath: jsURL.path), fileManager.fileExists(atPath: cssURL.path) else {
        FileHandle.standardError.write(Data("vendor/katex files missing under \(vendor.path)\n".utf8))
        exit(1)
    }

    let css = try base64(cssURL)
    let js = try base64(jsURL)
    let fonts = try fileManager
        .contentsOfDirectory(atPath: fontsDir.path)
        .filter { $0.hasSuffix(".woff2") }
        .sorted()

    var fontEntries: [String] = []
    for name in fonts {
        let encoded = try base64(fontsDir.appendingPathComponent(name))
        fontEntries.append("        \"\(name)\": \"\(encoded)\",")
    }

    let content = """
    // AUTO-GENERATED by ArcAssetTool — do not edit by hand.
    // ArcAssetPlugin regenerates this on every build from
    // Sources/ArcAgentWebUI/Assets/vendor/katex/.
    import Foundation

    /// KaTeX (typesets $..$ / $$..$$ math in message bodies) vendored from the
    /// Arc Agent web UI (vendor/katex/0.16.22), embedded base64 so the release
    /// binary remains single-file and no string escaping can corrupt the payloads.
    public enum KaTeXAssets {
        public static let jsURL = "/ui/vendor/katex/katex.min.js"
        public static let cssURL = "/ui/vendor/katex/katex.min.css"
        public static let cssBase64 = "\(css)"

        public static var css: String {
            guard let data = Data(base64Encoded: cssBase64),
                  let text = String(data: data, encoding: .utf8) else { return "" }
            return text
        }

        public static var js: String {
            guard let data = Data(base64Encoded: jsBase64),
                  let text = String(data: data, encoding: .utf8) else { return "" }
            return text
        }

        private static let jsBase64 = "\(js)"

        /// Base64-encoded woff2 font files referenced by katex.min.css.
        public static let fontsBase64: [String: String] = [
    \(fontEntries.joined(separator: "\n"))
        ]
    }

    """

    try write(content, to: output)
    print("  \(fonts.count) fonts")
}

// MARK: - theme sheet

/// gzip in-memory bytes with the host `gzip`, or nil when the host has none.
///
/// `-n` is not cosmetic: it drops the file name and timestamp from the header, so the same
/// bytes produce the same gzip stream on every build and on every machine — which is what
/// lets a content-addressed url stay stable. `-9` because this runs once per build.
func gzipData(_ data: Data) -> Data? {
    let tmp = fileManager.temporaryDirectory.appendingPathComponent("arctheme-\(UUID().uuidString).css")
    guard (try? data.write(to: tmp)) != nil else { return nil }
    defer { try? fileManager.removeItem(at: tmp) }

    let process = Process()
    process.executableURL = URL(fileURLWithPath: "/usr/bin/gzip")
    process.arguments = ["-n", "-9", "-c", tmp.path]
    let out = Pipe()
    process.standardOutput = out
    process.standardError = Pipe()
    do {
        try process.run()
    } catch {
        return nil
    }
    // drain before waiting: a payload larger than the pipe buffer would deadlock otherwise.
    let gz = out.fileHandleForReading.readDataToEndOfFile()
    process.waitUntilExit()
    guard process.terminationStatus == 0, !gz.isEmpty else { return nil }
    return gz
}

func generateThemeSheet(output: URL) throws {
    // the same expression the runtime used to evaluate per boot — rendered once, here, so the
    // url, the bytes and the hash that names them cannot disagree.
    let sheet = Theme.css + ArcThemeCatalog.stylesheet()
    let raw = Data(sheet.utf8)
    let stamp = SHA256.hash(data: raw).map { String(format: "%02x", $0) }.joined().prefix(12)
    let gz = gzipData(raw)

    let content = """
    // AUTO-GENERATED by ArcAssetTool — do not edit by hand.
    // ArcAssetPlugin regenerates this on every build from Sources/ArcTheme/.
    import Foundation

    /// The served stylesheet: arc's chrome sheet plus the 27-scheme catalog blocks, with its
    /// content address and its pre-compressed form.
    ///
    /// A build product of `Sources/ArcTheme/`, so the url a page links, the bytes the server
    /// serves and the sha256 that names them cannot drift apart — the runtime neither renders
    /// nor compresses the sheet, and a palette edit that reaches the source reaches the wire.
    ///
    /// `Tests/ArcAgentWebUITests` pins `sheet` against `Theme.css + ArcThemeCatalog.stylesheet()`,
    /// so a plugin that silently stopped re-running fails the suite rather than the page.
    public enum ThemeSheetAssets {
        /// the sha256 prefix these bytes are served under: `/ui/style.css?v=<stamp>`.
        public static let stamp = "\(stamp)"

        /// the sheet, base64 like every embedded payload here: a raw string literal would drop
        /// the sheet's final newline (the line before the closing delimiter is the delimiter's
        /// own), and an off-by-one byte is an off-by-one content address.
        private static let sheetBase64 = "\(raw.base64EncodedString())"

        public static let sheet: String = {
            guard let data = Data(base64Encoded: sheetBase64),
                  let text = String(data: data, encoding: .utf8) else { return "" }
            return text
        }()

        /// the same bytes, gzipped at build time. empty when the build host has no `gzip`.
        private static let gzipBase64 = "\(gz?.base64EncodedString() ?? "")"

        /// the pre-compressed variant, or empty when the build host had no `gzip` — the
        /// server then serves the uncompressed form and emits no `Vary`.
        public static let gzip: [UInt8] = {
            guard let data = Data(base64Encoded: gzipBase64) else { return [] }
            return [UInt8](data)
        }()
    }

    """

    try write(content, to: output)
    print("  sheet \(raw.count) bytes, stamp \(stamp), gzip \(gz?.count ?? 0) bytes")
}

// MARK: - entry

guard arguments.count >= 2 else { usage() }

do {
    switch arguments[1] {
    case "katex":
        guard arguments.count == 4 else { usage() }
        try generateKatex(vendor: URL(fileURLWithPath: arguments[2], isDirectory: true), output: URL(fileURLWithPath: arguments[3]))
    case "theme-sheet":
        guard arguments.count == 3 else { usage() }
        try generateThemeSheet(output: URL(fileURLWithPath: arguments[2]))
    default:
        usage()
    }
} catch {
    FileHandle.standardError.write(Data("ArcAssetTool: \(error)\n".utf8))
    exit(1)
}