import Foundation

// Generates `KaTeXAssets.swift` from the vendored KaTeX files.
//
// Everything is embedded base64 so the release binary stays a single file and
// no escaping issue can corrupt the JS/CSS payloads (the patch/write transport
// double-escapes backslashes; base64 sidesteps that entirely).
//
// Invoked by `ArcAssetPlugin` on every build — there is no shell script and no
// hand-run step. `usage: ArcAssetTool <vendor/katex> <out.swift>`

let arguments = CommandLine.arguments
guard arguments.count == 3 else {
    FileHandle.standardError.write(Data("usage: ArcAssetTool <vendor/katex> <out.swift>\n".utf8))
    exit(2)
}

let vendor = URL(fileURLWithPath: arguments[1], isDirectory: true)
let output = URL(fileURLWithPath: arguments[2])
let fileManager = FileManager.default

func base64(_ url: URL) throws -> String {
    try Data(contentsOf: url).base64EncodedString()
}

do {
    let jsURL = vendor.appendingPathComponent("katex.min.js")
    let cssURL = vendor.appendingPathComponent("katex.min.css")
    let fontsDir = vendor.appendingPathComponent("fonts", isDirectory: true)

    guard fileManager.fileExists(atPath: jsURL.path), fileManager.fileExists(atPath: cssURL.path) else {
        FileHandle.standardError.write(Data("vendor/katex files missing under \(vendor.path)\n".utf8))
        exit(1)
    }

    let css = try base64(cssURL)
    let js = try base64(jsURL)
    let fonts = try fileManager
        .contentsOfDirectory(atPath: fontsDir.path)
        .filter { $0.hasSuffix(".woff2") }
        .sorted()

    var fontEntries: [String] = []
    for name in fonts {
        let encoded = try base64(fontsDir.appendingPathComponent(name))
        fontEntries.append("        \"\(name)\": \"\(encoded)\",")
    }

    let content = """
    // AUTO-GENERATED by ArcAssetTool — do not edit by hand.
    // ArcAssetPlugin regenerates this on every build from
    // Sources/ArcAgentWebUI/Assets/vendor/katex/.
    import Foundation

    /// KaTeX (typesets $..$ / $$..$$ math in message bodies) vendored from the
    /// Arc Agent web UI (vendor/katex/0.16.22), embedded base64 so the release
    /// binary remains single-file and no string escaping can corrupt the payloads.
    public enum KaTeXAssets {
        public static let jsURL = "/ui/vendor/katex/katex.min.js"
        public static let cssURL = "/ui/vendor/katex/katex.min.css"
        public static let cssBase64 = "\(css)"

        public static var css: String {
            guard let data = Data(base64Encoded: cssBase64),
                  let text = String(data: data, encoding: .utf8) else { return "" }
            return text
        }

        public static var js: String {
            guard let data = Data(base64Encoded: jsBase64),
                  let text = String(data: data, encoding: .utf8) else { return "" }
            return text
        }

        private static let jsBase64 = "\(js)"

        /// Base64-encoded woff2 font files referenced by katex.min.css.
        public static let fontsBase64: [String: String] = [
    \(fontEntries.joined(separator: "\n"))
        ]
    }

    """

    try fileManager.createDirectory(
        at: output.deletingLastPathComponent(),
        withIntermediateDirectories: true
    )
    try Data(content.utf8).write(to: output)
    print("wrote \(output.path) (\(content.utf8.count) bytes, \(fonts.count) fonts)")
} catch {
    FileHandle.standardError.write(Data("ArcAssetTool: \(error)\n".utf8))
    exit(1)
}