#!/usr/bin/env python3
"""Generate Sources/ArcAgentWebUI/Generated/KaTeXAssets.swift from the
vendored KaTeX files in Sources/ArcAgentWebUI/Assets/vendor/katex/.

Everything is embedded base64 so the release binary stays a single file and no
escaping issue can corrupt the JS/CSS strings (the patch/write transport
double-escapes backslashes; base64 sidesteps that entirely). Run after any
vendor/katex update: `python3 Scripts/gen_katex_assets.py`.
"""
import base64
import os
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
VENDOR = ROOT / "Sources/ArcAgentWebUI/Assets/vendor/katex"
OUT_DIR = ROOT / "Sources/ArcAgentWebUI/Generated"
OUT = OUT_DIR / "KaTeXAssets.swift"


def b64(path: Path) -> str:
    data = path.read_bytes()
    return base64.b64encode(data).decode("ascii")


def main() -> None:
    js = VENDOR / "katex.min.js"
    css = VENDOR / "katex.min.css"
    fonts = sorted((VENDOR / "fonts").glob("*.woff2"))
    assert js.exists() and css.exists(), "vendor/katex files missing"

    entries = []
    for f in fonts:
        entries.append(f'        "{f.name}": "{b64(f)}",')
    fonts_block = "\n".join(entries)

    content = f"""// AUTO-GENERATED by Scripts/gen_katex_assets.py — do not edit by hand.
// Regenerate after updating Sources/ArcAgentWebUI/Assets/vendor/katex/.
import Foundation

/// KaTeX (typesets $..$ / $$..$$ math in message bodies) vendored from the
/// Hermes WebUI (vendor/katex/0.16.22), embedded base64 so the release binary
/// remains single-file and no string escaping can corrupt the payloads.
public enum KaTeXAssets {{
    public static let jsURL = "/ui/vendor/katex/katex.min.js"
    public static let cssURL = "/ui/vendor/katex/katex.min.css"
    public static let cssBase64 = "{b64(css)}"

    public static var css: String {{
        guard let data = Data(base64Encoded: cssBase64),
              let text = String(data: data, encoding: .utf8) else {{ return "" }}
        return text
    }}

    public static var js: String {{
        guard let data = Data(base64Encoded: jsBase64),
              let text = String(data: data, encoding: .utf8) else {{ return "" }}
        return text
    }}

    private static let jsBase64 = "{b64(js)}"

    /// Base64-encoded woff2 font files referenced by katex.min.css.
    public static let fontsBase64: [String: String] = [
{fonts_block}
    ]
}}
"""
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    OUT.write_text(content)
    print(f"wrote {OUT} ({len(content)} bytes, {len(fonts)} fonts)")


if __name__ == "__main__":
    main()
